name: CI

on:
  push:
  pull_request:

jobs:

  publish:
    uses: astrofrog/github-actions-workflows/.github/workflows/publish.yml@fix-sdist-publish
    with:
      repository_url: https://test.pypi.org/legacy/
      sdist-runs-on: ubuntu-22.04
      targets: |
        - cp39-manylinux_x86_64
    secrets:
      pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
